version: "3"
services:

  php-fpm:
    build:
      context: ./deployment/docker/php-fpm
    volumes:
      - ./:/var/www
    container_name: php-fpm

  nginx:
    build:
      context: ./deployment/docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./deployment/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/docker/nginx/sites/:/etc/nginx/sites-available
      - ./deployment/docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    container_name: nginx

  mysql:
    build:
      context: ./deployment/docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./persistent_data/mysql:/var/lib/mysql
    container_name: mysql

  mysql_testing:
    build:
      context: ./deployment/docker/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: chat_testing
      MYSQL_USER: chat_testing
      MYSQL_PASSWORD: chat_testing
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql_testing

  redis:
    build:
      context: ./deployment/docker/redis
    volumes:
      - ./persistent_data/redis:/data
    ports:
      - "6379:6379"
    container_name: redis

#  laravel-echo-server:
#    build:
#      context: ./deployment/docker/laravel-echo-server
#    volumes:
#      - ./deployment/docker/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
#    ports:
#      - "6001:6001"
#    depends_on:
#      - redis
#    container_name: laravel-echo-server

  phpmyadmin:
    build: ./deployment/docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=chat
      - MYSQL_PASSWORD=chat
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    container_name: pma
